server {
    listen 80;
    server_name haribol.yuktaa.com;

    root /home/ubuntu/chaitanyabhakti/frontend/build;
    index index.html;

    # Frontend - Serve React App
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Backend - Proxy API requests
    location /api/ {
        proxy_pass http://localhost:5000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
